# Generated by Django 6.0.1 on 2026-01-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_readingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbook',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Note de 1 à 5', null=True),
        ),
    ]
